source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'CocoPod_Example' do
pod 'AFNetworking', '~> 3.1.0'

  pod 'CocoPod', :path => '../'

  target 'CocoPod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
